"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Define o diretório base do projeto. Ajuda a construir caminhos relativos dentro do projeto.
BASE_DIR = Path(__file__).resolve().parent.parent


# Configurações de desenvolvimento rápido - não adequadas para produção
# Veja https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# AVISO DE SEGURANÇA: mantenha a chave secreta usada em produção em segredo!
# Esta é uma chave única usada para fins de segurança, como hashes de senha e proteção CSRF.
SECRET_KEY = 'django-insecure-@eta%gz6*q28vtr0ijv0c37uxa4f27ds@-y07nh1=kjr@#+nh$'

# AVISO DE SEGURANÇA: não execute com o modo DEBUG ativado em produção!
# DEBUG = True ativa o modo de depuração, mostrando informações detalhadas de erro.
# Deve ser False em produção para evitar a exposição de informações sensíveis.
DEBUG = True

# Uma lista de strings que representam os nomes de host/domínio que este site pode servir.
# Em produção, deve conter os domínios do seu site (ex: ['www.example.com']).
ALLOWED_HOSTS = []


# Definição das aplicações (aplicativos)

# Lista de aplicações Django ativadas para este projeto.
# Inclui as aplicações padrão do Django (admin, autenticação, sessões, etc.)
# e as aplicações personalizadas do seu projeto ('home', 'blog').
INSTALLED_APPS = [
    'django.contrib.admin',  # Interface de administração do Django.
    'django.contrib.auth',  # Sistema de autenticação e permissões.
    'django.contrib.contenttypes',  # Framework para tipos de conteúdo.
    'django.contrib.sessions',  # Framework de sessões.
    'django.contrib.messages',  # Framework de mensagens.
    'django.contrib.staticfiles',  # Gerenciamento de arquivos estáticos.
    'home',  # Aplicação personalizada 'home'.
    'blog',  # Aplicação personalizada 'blog'.
]

# Middleware são componentes que processam requisições e respostas.
# Esta lista define a ordem em que eles são executados.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Recursos de segurança.
    'django.contrib.sessions.middleware.SessionMiddleware',  # Habilita suporte a sessões.
    'django.middleware.common.CommonMiddleware',  # Adiciona barras e lida com algumas regras HTTP.
    'django.middleware.csrf.CsrfViewMiddleware',  # Proteção contra Cross-Site Request Forgery.
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Associa usuários a requisições usando sessões.
    'django.contrib.messages.middleware.MessageMiddleware',  # Habilita suporte a mensagens baseadas em cookie.
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Proteção contra clickjacking.
]

# O módulo de URL raiz do projeto. Django procurará 'urlpatterns' neste módulo.
ROOT_URLCONF = 'project.urls'

# Configuração dos motores de template.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Diretórios onde o Django deve procurar arquivos de template.
        # BASE_DIR / 'base' adiciona o diretório 'base' na raiz do projeto.
        'DIRS': [
            BASE_DIR / 'base'
        ],
        # Permite que o Django procure templates dentro dos diretórios 'templates' das apps.
        'APP_DIRS': True,
        'OPTIONS': {
            # Processadores de contexto são funções que adicionam variáveis ao contexto do template.
            'context_processors': [
                'django.template.context_processors.debug',  # Adiciona variáveis relacionadas ao DEBUG.
                'django.template.context_processors.request',  # Adiciona o objeto request ao contexto.
                'django.contrib.auth.context_processors.auth',  # Adiciona variáveis relacionadas ao usuário logado.
                'django.contrib.messages.context_processors.messages',  # Adiciona mensagens do framework de mensagens.
            ],
        },
    },
]

# Aplicação WSGI (Web Server Gateway Interface) para servir seu projeto.
# Usado por servidores web como Gunicorn e uWSGI.
WSGI_APPLICATION = 'project.wsgi.application'


# Banco de Dados
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Configuração do banco de dados. Por padrão, usa SQLite3.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Motor do banco de dados (SQLite3 é o padrão e bom para desenvolvimento).
        'NAME': BASE_DIR / 'db.sqlite3',  # Caminho para o arquivo do banco de dados SQLite.
    }
}


# Validação de senha
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# Validadores usados para verificar a força das senhas dos usuários.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        # Impede senhas muito semelhantes a atributos do usuário.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        # Requer um comprimento mínimo para a senha.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        # Impede senhas comumente usadas.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        # Impede senhas que são apenas números.
    },
]


# Internacionalização
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# Código de idioma padrão para este projeto.
LANGUAGE_CODE = 'en-us'

# Fuso horário padrão para este projeto. 'UTC' é uma boa prática.
TIME_ZONE = 'UTC'

# Ativa o sistema de internacionalização do Django.
USE_I18N = True

# Ativa o suporte a fusos horários.
USE_TZ = True


# Arquivos estáticos (CSS, JavaScript, Imagens)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# URL para servir arquivos estáticos.
STATIC_URL = 'static/'
# Diretórios adicionais onde o Django deve procurar arquivos estáticos.
# Aqui, ele procura em 'base/static' na raiz do projeto.
STATICFILES_DIRS = [
    BASE_DIR / 'base' / 'static'
]
# https://whitenoise.readthedocs.io/en/latest/
# O diretório onde os arquivos estáticos serão coletados para implantação.
# Deve ser configurado em produção (ex: `python manage.py collectstatic`).
STATIC_ROOT = BASE_DIR / 'static_files'

# Tipo de campo de chave primária padrão
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# Define o tipo de campo de chave primária padrão para modelos que não especificam um.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
